# Generated by Django 4.2.6 on 2024-02-25 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hello_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hello",
            name="population",
            field=models.BigIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
    ]
